[package]
name = "wasm-isolate"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.28", features = ["derive"] }
wasm-encoder = "0.225.0"
wasmparser = "0.225.0"
