// This file is automatically generated. DO NOT EDIT.
package parser

func _memop(_s *Stream) (*Phrase[int], int, int) {
	__tmp1 := _pos(_s)
	_pos := __tmp1
	__tmp2 := _u32(_s)
	_flags := __tmp2
	__tmp3 := _require_4((_flags) < (0x80), _s, _pos, "malformed memop flags")
	_ = __tmp3
	__tmp5 := (_flags)&(0x40) != 0
	_has_var := __tmp5
	var __tmp7 any
	if _has_var {
		__tmp8 := _at_2(_var, _s)
		__tmp7 = __tmp8
	} else {
		__tmp9 := _operatorAtAt_2(0, _no_region)
		__tmp7 = __tmp9
	}
	_x := __tmp7
	__tmp10 := _to_int(_logand_2(_flags, 0x3f))
	_align := __tmp10
	__tmp12 := _u64(_s)
	_offset := __tmp12
	return _x, _align, _offset
}
